schwz::SchwarzBase< ValueType, IndexType, MixedValueType > Class Template Reference
The Base solver class is meant to be the class implementing the common implementations for all the schwarz methods.
#include <schwarz_base.hpp>
Public Member Functions
SchwarzBase (Settings &settings, Metadata< ValueType, IndexType > &metadata)
The constructor that takes in the user settings and a metadata struct containing the solver metadata.
void initialize ()
Initialize the matrix and vectors.
void run (std::shared_ptr< gko::matrix::Dense< ValueType >> &solution)
The function that runs the actual solver and obtains the final solution.
void print_vector (const std::shared_ptr< gko::matrix::Dense< ValueType >> &vector, int subd, std::string name)
The auxiliary function that prints a passed in vector.
void print_matrix (const std::shared_ptr< gko::matrix::Csr< ValueType, IndexType >> &matrix, int rank, std::string name)
The auxiliary function that prints a passed in CSR matrix.
Public Attributes
std::shared_ptr< gko::matrix::Csr< ValueType, IndexType > > local_matrix
The local subdomain matrix.
std::shared_ptr< gko::matrix::Permutation< IndexType > > local_perm
The local subdomain permutation matrix/array.
std::shared_ptr< gko::matrix::Permutation< IndexType > > local_inv_perm
The local subdomain inverse permutation matrix/array.
std::shared_ptr< gko::matrix::Csr< ValueType, IndexType > > triangular_factor_l
The local lower triangular factor used for the triangular solves.
std::shared_ptr< gko::matrix::Csr< ValueType, IndexType > > triangular_factor_u
The local upper triangular factor used for the triangular solves.
std::shared_ptr< gko::matrix::Csr< ValueType, IndexType > > interface_matrix
The local interface matrix.
std::shared_ptr< gko::matrix::Csr< ValueType, IndexType > > global_matrix
The global matrix.
std::shared_ptr< gko::matrix::Dense< ValueType > > local_rhs
The local right hand side.
std::shared_ptr< gko::matrix::Dense< ValueType > > global_rhs
The global right hand side.
std::shared_ptr< gko::matrix::Dense< ValueType > > local_solution
The local solution vector.
std::shared_ptr< gko::matrix::Dense< ValueType > > prev_event_solution
The (local+overlap) solution vector at time of previous event of communication The size of this vector is considered global_size to account for overlap.
std::shared_ptr< gko::matrix::Dense< ValueType > > global_solution
The global solution vector.
std::vector< ValueType > local_residual_vector_out
The global residual vector.
std::vector< std::vector< ValueType > > global_residual_vector_out
The local residual vector.
Additional Inherited Members
Detailed Description
template<typename ValueType = gko::default_precision, typename IndexType = gko::int32, typename MixedValueType = gko::default_precision>
class schwz::SchwarzBase< ValueType, IndexType, MixedValueType >
The Base solver class is meant to be the class implementing the common implementations for all the schwarz methods.
It derives from the Initialization class, the Communication class and the Solve class all of which are templated.
Template Parameters
ValueType The type of the floating point values.
IndexType The type of the index type values.
Constructor & Destructor Documentation
SchwarzBase()
template<typename ValueType , typename IndexType , typename MixedValueType >
schwz::SchwarzBase< ValueType, IndexType, MixedValueType >::SchwarzBase (Settings & settings, Metadata< ValueType, IndexType > & metadata)
The constructor that takes in the user settings and a metadata struct containing the solver metadata.
Parameters
settings The settings struct.
metadata The metadata struct.
References schwz::Settings::cuda_device_guard, schwz::Settings::executor, schwz::Settings::executor_string, schwz::Metadata< ValueType, IndexType >::local_num_procs, schwz::Metadata< ValueType, IndexType >::mpi_communicator, schwz::Metadata< ValueType, IndexType >::my_local_rank, and schwz::Metadata< ValueType, IndexType >::my_rank.
Member Function Documentation
print_matrix()
template<typename ValueType = gko::default_precision, typename IndexType = gko::int32, typename MixedValueType = gko::default_precision>
void schwz::SchwarzBase< ValueType, IndexType, MixedValueType >::print_matrix (const std::shared_ptr< gko::matrix::Csr< ValueType, IndexType >> & matrix, int rank, std::string name)
The auxiliary function that prints a passed in CSR matrix.
Parameters
matrix The matrix to be printed.
subd The subdomain on which the vector exists.
name The name of the matrix as a string.
print_vector()
template<typename ValueType = gko::default_precision, typename IndexType = gko::int32, typename MixedValueType = gko::default_precision>
void schwz::SchwarzBase< ValueType, IndexType, MixedValueType >::print_vector (const std::shared_ptr< gko::matrix::Dense< ValueType >> & vector, int subd, std::string name)
The auxiliary function that prints a passed in vector.
Parameters
vector The vector to be printed.
subd The subdomain on which the vector exists.
name The name of the vector as a string.
run()
template<typename ValueType , typename IndexType , typename MixedValueType >
void schwz::SchwarzBase< ValueType, IndexType, MixedValueType >::run (std::shared_ptr< gko::matrix::Dense< ValueType >> & solution)
The function that runs the actual solver and obtains the final solution.
Parameters
solution The solution vector.
References schwz::Settings::debug_print, schwz::Settings::event_log_print, schwz::Communicate< ValueType, IndexType, MixedValueType >::exchange_boundary(), schwz::Settings::executor, schwz::Settings::executor_string, schwz::SchwarzBase< ValueType, IndexType, MixedValueType >::global_matrix, schwz::SchwarzBase< ValueType, IndexType, MixedValueType >::global_rhs, schwz::SchwarzBase< ValueType, IndexType, MixedValueType >::global_solution, schwz::SchwarzBase< ValueType, IndexType, MixedValueType >::interface_matrix, schwz::SchwarzBase< ValueType, IndexType, MixedValueType >::local_inv_perm, schwz::SchwarzBase< ValueType, IndexType, MixedValueType >::local_matrix, schwz::SchwarzBase< ValueType, IndexType, MixedValueType >::local_perm, schwz::SchwarzBase< ValueType, IndexType, MixedValueType >::local_rhs, schwz::SchwarzBase< ValueType, IndexType, MixedValueType >::local_solution, schwz::Communicate< ValueType, IndexType, MixedValueType >::local_to_global_vector(), schwz::Communicate< ValueType, IndexType, MixedValueType >::comm_struct::msg_count, schwz::Communicate< ValueType, IndexType, MixedValueType >::comm_struct::neighbors_out, schwz::Communicate< ValueType, IndexType, MixedValueType >::comm_struct::num_neighbors_out, schwz::Settings::overlap, schwz::SchwarzBase< ValueType, IndexType, MixedValueType >::prev_event_solution, schwz::Communicate< ValueType, IndexType, MixedValueType >::setup_windows(), schwz::Settings::comm_settings::stage_through_host, schwz::Settings::thres_type, schwz::SchwarzBase< ValueType, IndexType, MixedValueType >::triangular_factor_l, schwz::SchwarzBase< ValueType, IndexType, MixedValueType >::triangular_factor_u, schwz::Communicate< ValueType, IndexType, MixedValueType >::update_boundary(), and schwz::Settings::write_iters_and_residuals.
The documentation for this class was generated from the following files:
schwarz_base.hpp (c9f1d38)
/home/runner/work/schwarz-lib/schwarz-lib/source/schwarz_base.cpp (96ebd2f)