SchwarzWrappers::Communicate< ValueType, IndexType > Class Template Reference
The communication class that provides the methods for the communication between the subdomains.
#include <communicate.hpp>
Classes
struct comm_struct
The communication struct used to store the communication data.
Public Member Functions
virtual void setup_comm_buffers ()=0
Sets up the communication buffers needed for the boundary exchange.
virtual void setup_windows (const Settings &settings, const Metadata< ValueType, IndexType > &metadata, std::shared_ptr< gko::matrix::Dense< ValueType >> &main_buffer)=0
Sets up the windows needed for the asynchronous communication.
virtual void exchange_boundary (const Settings &settings, const Metadata< ValueType, IndexType > &metadata, std::shared_ptr< gko::matrix::Dense< ValueType >> &solution_vector)=0
Exchanges the elements of the solution vector.
void local_to_global_vector (const Settings &settings, const Metadata< ValueType, IndexType > &metadata, const std::shared_ptr< gko::matrix::Dense< ValueType >> &local_vector, std::shared_ptr< gko::matrix::Dense< ValueType >> &global_vector)
Transforms data from a local vector to a global vector.
virtual void update_boundary (const Settings &settings, const Metadata< ValueType, IndexType > &metadata, std::shared_ptr< gko::matrix::Dense< ValueType >> &local_solution, const std::shared_ptr< gko::matrix::Dense< ValueType >> &local_rhs, const std::shared_ptr< gko::matrix::Dense< ValueType >> &solution_vector, std::shared_ptr< gko::matrix::Dense< ValueType >> &global_old_solution, const std::shared_ptr< gko::matrix::Csr< ValueType, IndexType >> &interface_matrix)=0
Update the values into local vector from obtained from the neighboring sub-domains using the interface matrix.
void clear (Settings &settings)
Clears the data.
Public Attributes
comm_struct comm_struct
Friends
class Initialize< ValueType, IndexType >
Detailed Description
template<typename ValueType, typename IndexType>
class SchwarzWrappers::Communicate< ValueType, IndexType >
The communication class that provides the methods for the communication between the subdomains.
Template Parameters
ValueType The type of the floating point values.
IndexType The type of the index type values.
Communicate
Member Function Documentation
exchange_boundary()
template<typename ValueType , typename IndexType >
void SchwarzWrappers::Communicate< ValueType, IndexType >::exchange_boundary (const Settings & settings, const Metadata< ValueType, IndexType > & metadata, std::shared_ptr< gko::matrix::Dense< ValueType >> & solution_vector) [pure virtual]
Exchanges the elements of the solution vector.
Parameters
settings The settings struct.
metadata The metadata struct.
solution_vector The solution vector being exchanged between the subdomains.
Implemented in SchwarzWrappers::SolverRAS< ValueType, IndexType >.
Referenced by SchwarzWrappers::SchwarzBase< ValueType, IndexType >::run().
local_to_global_vector()
template<typename ValueType , typename IndexType >
void SchwarzWrappers::Communicate< ValueType, IndexType >::local_to_global_vector (const Settings & settings, const Metadata< ValueType, IndexType > & metadata, const std::shared_ptr< gko::matrix::Dense< ValueType >> & local_vector, std::shared_ptr< gko::matrix::Dense< ValueType >> & global_vector)
Transforms data from a local vector to a global vector.
Parameters
settings The settings struct.
metadata The metadata struct.
local_vector The local vector in question.
global_vector The global vector in question.
setup_windows()
template<typename ValueType , typename IndexType >
void SchwarzWrappers::Communicate< ValueType, IndexType >::setup_windows (const Settings & settings, const Metadata< ValueType, IndexType > & metadata, std::shared_ptr< gko::matrix::Dense< ValueType >> & main_buffer) [pure virtual]
Sets up the windows needed for the asynchronous communication.
Parameters
settings The settings struct.
metadata The metadata struct.
main_buffer The main buffer being exchanged between the subdomains.
Implemented in SchwarzWrappers::SolverRAS< ValueType, IndexType >.
Referenced by SchwarzWrappers::SchwarzBase< ValueType, IndexType >::run().
update_boundary()
template<typename ValueType , typename IndexType >
void SchwarzWrappers::Communicate< ValueType, IndexType >::update_boundary (const Settings & settings, const Metadata< ValueType, IndexType > & metadata, std::shared_ptr< gko::matrix::Dense< ValueType >> & local_solution, const std::shared_ptr< gko::matrix::Dense< ValueType >> & local_rhs, const std::shared_ptr< gko::matrix::Dense< ValueType >> & solution_vector, std::shared_ptr< gko::matrix::Dense< ValueType >> & global_old_solution, const std::shared_ptr< gko::matrix::Csr< ValueType, IndexType >> & interface_matrix) [pure virtual]
Update the values into local vector from obtained from the neighboring sub-domains using the interface matrix.
Parameters
settings The settings struct.
metadata The metadata struct.
local_solution The local solution vector in the subdomain.
local_rhs The local right hand side vector in the subdomain.
solution_vector The workspace solution vector.
global_old_solution The global solution vector of the previous iteration.
interface_matrix The interface matrix containing the interface and the overlap data mainly used for exchanging values between different sub-domains.
Implemented in SchwarzWrappers::SolverRAS< ValueType, IndexType >.
Referenced by SchwarzWrappers::SchwarzBase< ValueType, IndexType >::run().
The documentation for this class was generated from the following files:
communicate.hpp (a4aae12)
/home/runner/work/schwarz-lib/schwarz-lib/source/communicate.cpp (a4aae12)