title: Schwarz Library
description: Schwarz Library is an implementation of the asynchronous Schwarz methods using Ginkgo.
show_downloads: true
github:
  zip_url: https://github.com/pratikvn/schwarz-lib/zipball/master
  tar_url: https://github.com/pratikvn/schwarz-lib/tarball/master
theme: jekyll-theme-minimal
