SchwarzWrappers::SchwarzBase< ValueType, IndexType > Class Template Reference
The Base solver class is meant to be the class implementing the common implementations for all the schwarz methods.
#include <schwarz_base.hpp>
Public Member Functions
SchwarzBase (Settings &settings, Metadata< ValueType, IndexType > &metadata)
The constructor that takes in the user settings and a metadata struct containing the solver metadata.
void initialize ()
Initialize the matrix and vectors.
void run (std::shared_ptr< gko::matrix::Dense< ValueType >> &solution)
The function that runs the actual solver and obtains the final solution.
void print_vector (const std::shared_ptr< gko::matrix::Dense< ValueType >> &vector, int subd, std::string name)
The auxiliary function that prints a passed in vector.
void print_matrix (const std::shared_ptr< gko::matrix::Csr< ValueType, IndexType >> &matrix, int rank, std::string name)
The auxiliary function that prints a passed in CSR matrix.
Public Attributes
std::shared_ptr< gko::matrix::Csr< ValueType, IndexType > > local_matrix
The local subdomain matrix.
std::shared_ptr< gko::matrix::Permutation< IndexType > > local_perm
The local subdomain permutation matrix/array.
std::shared_ptr< gko::matrix::Permutation< IndexType > > local_inv_perm
The local subdomain inverse permutation matrix/array.
std::shared_ptr< gko::matrix::Csr< ValueType, IndexType > > triangular_factor
The local triangular factor used for the triangular solves.
std::shared_ptr< gko::matrix::Csr< ValueType, IndexType > > interface_matrix
The local interface matrix.
std::shared_ptr< gko::matrix::Csr< ValueType, IndexType > > global_matrix
The global matrix.
std::shared_ptr< gko::matrix::Dense< ValueType > > local_rhs
The local right hand side.
std::shared_ptr< gko::matrix::Dense< ValueType > > global_rhs
The global right hand side.
std::shared_ptr< gko::matrix::Dense< ValueType > > local_solution
The local solution vector.
std::shared_ptr< gko::matrix::Dense< ValueType > > global_solution
The global solution vector.
Additional Inherited Members
Detailed Description
template<typename ValueType = gko::default_precision, typename IndexType = gko::int32>
class SchwarzWrappers::SchwarzBase< ValueType, IndexType >
The Base solver class is meant to be the class implementing the common implementations for all the schwarz methods.
It derives from the Initialization class, the Communication class and the Solve class all of which are templated.
Template Parameters
ValueType The type of the floating point values.
IndexType The type of the index type values.
Constructor & Destructor Documentation
SchwarzBase()
template<typename ValueType , typename IndexType >
SchwarzWrappers::SchwarzBase< ValueType, IndexType >::SchwarzBase (Settings & settings, Metadata< ValueType, IndexType > & metadata)
The constructor that takes in the user settings and a metadata struct containing the solver metadata.
Parameters
settings The settings struct.
metadata The metadata struct.
References SchwarzWrappers::Metadata< ValueType, IndexType >::comm_size, SchwarzWrappers::Settings::cuda_device_guard, SchwarzWrappers::Settings::executor, SchwarzWrappers::Settings::executor_string, SchwarzWrappers::Metadata< ValueType, IndexType >::first_row, SchwarzWrappers::Communicate< ValueType, IndexType >::comm_struct::get_displacements, SchwarzWrappers::Communicate< ValueType, IndexType >::comm_struct::global_get, SchwarzWrappers::Communicate< ValueType, IndexType >::comm_struct::global_put, SchwarzWrappers::Metadata< ValueType, IndexType >::global_size, SchwarzWrappers::Metadata< ValueType, IndexType >::global_to_local, SchwarzWrappers::Metadata< ValueType, IndexType >::i_permutation, SchwarzWrappers::Communicate< ValueType, IndexType >::comm_struct::is_local_neighbor, SchwarzWrappers::Communicate< ValueType, IndexType >::comm_struct::local_neighbors_in, SchwarzWrappers::Communicate< ValueType, IndexType >::comm_struct::local_neighbors_out, SchwarzWrappers::Metadata< ValueType, IndexType >::local_num_procs, SchwarzWrappers::Metadata< ValueType, IndexType >::local_to_global, SchwarzWrappers::Metadata< ValueType, IndexType >::mpi_communicator, SchwarzWrappers::Metadata< ValueType, IndexType >::my_local_rank, SchwarzWrappers::Metadata< ValueType, IndexType >::my_rank, SchwarzWrappers::Communicate< ValueType, IndexType >::comm_struct::neighbors_in, SchwarzWrappers::Communicate< ValueType, IndexType >::comm_struct::neighbors_out, SchwarzWrappers::Metadata< ValueType, IndexType >::num_subdomains, SchwarzWrappers::Metadata< ValueType, IndexType >::permutation, and SchwarzWrappers::Communicate< ValueType, IndexType >::comm_struct::put_displacements.
Member Function Documentation
print_matrix()
template<typename ValueType = gko::default_precision, typename IndexType = gko::int32>
void SchwarzWrappers::SchwarzBase< ValueType, IndexType >::print_matrix (const std::shared_ptr< gko::matrix::Csr< ValueType, IndexType >> & matrix, int rank, std::string name)
The auxiliary function that prints a passed in CSR matrix.
Parameters
matrix The matrix to be printed.
subd The subdomain on which the vector exists.
name The name of the matrix as a string.
print_vector()
template<typename ValueType = gko::default_precision, typename IndexType = gko::int32>
void SchwarzWrappers::SchwarzBase< ValueType, IndexType >::print_vector (const std::shared_ptr< gko::matrix::Dense< ValueType >> & vector, int subd, std::string name)
The auxiliary function that prints a passed in vector.
Parameters
vector The vector to be printed.
subd The subdomain on which the vector exists.
name The name of the vector as a string.
run()
template<typename ValueType , typename IndexType >
void SchwarzWrappers::SchwarzBase< ValueType, IndexType >::run (std::shared_ptr< gko::matrix::Dense< ValueType >> & solution)
The function that runs the actual solver and obtains the final solution.
Parameters
solution The solution vector.
References SchwarzWrappers::Communicate< ValueType, IndexType >::exchange_boundary(), SchwarzWrappers::Settings::executor, SchwarzWrappers::SchwarzBase< ValueType, IndexType >::global_matrix, SchwarzWrappers::SchwarzBase< ValueType, IndexType >::global_rhs, SchwarzWrappers::SchwarzBase< ValueType, IndexType >::interface_matrix, SchwarzWrappers::SchwarzBase< ValueType, IndexType >::local_inv_perm, SchwarzWrappers::SchwarzBase< ValueType, IndexType >::local_matrix, SchwarzWrappers::SchwarzBase< ValueType, IndexType >::local_perm, SchwarzWrappers::SchwarzBase< ValueType, IndexType >::local_rhs, SchwarzWrappers::SchwarzBase< ValueType, IndexType >::local_solution, SchwarzWrappers::Communicate< ValueType, IndexType >::setup_windows(), SchwarzWrappers::SchwarzBase< ValueType, IndexType >::triangular_factor, and SchwarzWrappers::Communicate< ValueType, IndexType >::update_boundary().
The documentation for this class was generated from the following files:
schwarz_base.hpp (e8c4423)
/home/runner/work/schwarz-lib/schwarz-lib/source/schwarz_base.cpp (e8c4423)