#!/bin/bash -l

for num_pe in 8
do 
  for comm in "onesided"
  do 
    for size in 144
    do
      for part in "regular"
      do 
        for constant in 1E-10
        do
          for gamma in 0.95
          do
            ./cpu_batch $num_pe $num_pe $comm reference $size 1000 iterative-ginkgo $part $constant $gamma
          done   
        done
      done 
    done
  done
done
