schwz::Initialize< ValueType, IndexType > Class Template Reference
The initialization class that provides methods for initialization of the solver.
#include <initialization.hpp>
Public Member Functions
Initialize (Settings &settings, Metadata< ValueType, IndexType > &metadata)
void generate_rhs (std::vector< ValueType > &rhs)
Generates the right hand side vector.
void setup_global_matrix (const std::string &filename, const gko::size_type &oned_laplacian_size, std::shared_ptr< gko::matrix::Csr< ValueType, IndexType >> &global_matrix)
Generates the 2D global laplacian matrix.
void partition (const Settings &settings, const Metadata< ValueType, IndexType > &metadata, const std::shared_ptr< gko::matrix::Csr< ValueType, IndexType >> &global_matrix, std::vector< unsigned int > &partition_indices)
The partitioning function.
void setup_vectors (const Settings &settings, const Metadata< ValueType, IndexType > &metadata, std::vector< ValueType > &rhs, std::shared_ptr< gko::matrix::Dense< ValueType >> &local_rhs, std::shared_ptr< gko::matrix::Dense< ValueType >> &global_rhs, std::shared_ptr< gko::matrix::Dense< ValueType >> &local_solution)
Setup the vectors with default values and allocate mameory if not allocated.
virtual void setup_local_matrices (Settings &settings, Metadata< ValueType, IndexType > &metadata, std::vector< unsigned int > &partition_indices, std::shared_ptr< gko::matrix::Csr< ValueType, IndexType >> &global_matrix, std::shared_ptr< gko::matrix::Csr< ValueType, IndexType >> &local_matrix, std::shared_ptr< gko::matrix::Csr< ValueType, IndexType >> &interface_matrix)=0
Sets up the local and the interface matrices from the global matrix and the partition indices.
Public Attributes
std::vector< unsigned int > partition_indices
The partition indices containing the subdomains to which each row(vertex) of the matrix(graph) belongs to.
std::vector< unsigned int > cell_weights
The cell weights for the partition algorithm.
Additional Inherited Members
Detailed Description
template<typename ValueType = gko::default_precision, typename IndexType = gko::int32>
class schwz::Initialize< ValueType, IndexType >
The initialization class that provides methods for initialization of the solver.
Template Parameters
ValueType The type of the floating point values.
IndexType The type of the index type values.
Initialization
Member Function Documentation
generate_rhs()
template<typename ValueType , typename IndexType >
void schwz::Initialize< ValueType, IndexType >::generate_rhs (std::vector< ValueType > & rhs)
Generates the right hand side vector.
Parameters
rhs The rhs vector.
References schwz::Initialize< ValueType, IndexType >::setup_global_matrix().
Referenced by schwz::SchwarzBase< ValueType, IndexType, MixedValueType >::initialize().
partition()
template<typename ValueType , typename IndexType >
void schwz::Initialize< ValueType, IndexType >::partition (const Settings & settings, const Metadata< ValueType, IndexType > & metadata, const std::shared_ptr< gko::matrix::Csr< ValueType, IndexType >> & global_matrix, std::vector< unsigned int > & partition_indices)
The partitioning function.
Allows the partition of the global matrix depending with METIS and a regular 1D decomposition.
Parameters
settings The settings struct.
metadata The metadata struct.
global_matrix The global matrix.
partition_indices The partition indices [OUTPUT].
References schwz::Metadata< ValueType, IndexType >::global_size, schwz::Metadata< ValueType, IndexType >::my_rank, schwz::Metadata< ValueType, IndexType >::num_subdomains, and schwz::Settings::write_debug_out.
Referenced by schwz::SchwarzBase< ValueType, IndexType, MixedValueType >::initialize().
setup_global_matrix()
template<typename ValueType , typename IndexType >
void schwz::Initialize< ValueType, IndexType >::setup_global_matrix (const std::string & filename, const gko::size_type & oned_laplacian_size, std::shared_ptr< gko::matrix::Csr< ValueType, IndexType >> & global_matrix)
Generates the 2D global laplacian matrix.
Parameters
oned_laplacian_size The size of the one d laplacian grid.
global_matrix The global matrix.
Referenced by schwz::Initialize< ValueType, IndexType >::generate_rhs(), and schwz::SchwarzBase< ValueType, IndexType, MixedValueType >::initialize().
setup_local_matrices()
template<typename ValueType , typename IndexType >
void schwz::Initialize< ValueType, IndexType >::setup_local_matrices (Settings & settings, Metadata< ValueType, IndexType > & metadata, std::vector< unsigned int > & partition_indices, std::shared_ptr< gko::matrix::Csr< ValueType, IndexType >> & global_matrix, std::shared_ptr< gko::matrix::Csr< ValueType, IndexType >> & local_matrix, std::shared_ptr< gko::matrix::Csr< ValueType, IndexType >> & interface_matrix) [pure virtual]
Sets up the local and the interface matrices from the global matrix and the partition indices.
Parameters
settings The settings struct.
metadata The metadata struct.
partition_indices The array containing the partition indices.
global_matrix The global system matrix.
local_matrix The local system matrix.
interface_matrix The interface matrix containing the interface and the overlap data mainly used for exchanging values between different sub-domains.
local_perm The local permutation, obtained through RCM or METIS.
Implemented in schwz::SolverRAS< ValueType, IndexType, MixedValueType >.
Referenced by schwz::SchwarzBase< ValueType, IndexType, MixedValueType >::initialize().
setup_vectors()
template<typename ValueType , typename IndexType >
void schwz::Initialize< ValueType, IndexType >::setup_vectors (const Settings & settings, const Metadata< ValueType, IndexType > & metadata, std::vector< ValueType > & rhs, std::shared_ptr< gko::matrix::Dense< ValueType >> & local_rhs, std::shared_ptr< gko::matrix::Dense< ValueType >> & global_rhs, std::shared_ptr< gko::matrix::Dense< ValueType >> & local_solution)
Setup the vectors with default values and allocate mameory if not allocated.
Parameters
settings The settings struct.
metadata The metadata struct.
local_rhs The local right hand side vector in the subdomain.
global_rhs The global right hand side vector.
local_solution The local solution vector in the subdomain.
References schwz::Settings::executor, schwz::Metadata< ValueType, IndexType >::first_row, schwz::Metadata< ValueType, IndexType >::local_size_x, and schwz::Metadata< ValueType, IndexType >::my_rank.
Referenced by schwz::SchwarzBase< ValueType, IndexType, MixedValueType >::initialize().
The documentation for this class was generated from the following files:
initialization.hpp (b5ec69e)
/home/runner/work/schwarz-lib/schwarz-lib/source/initialization.cpp (b5ec69e)