name: Build-doc

on: [push]

jobs:
  build:

    name: Doxygen build
    runs-on: [ubuntu-latest]
    
    steps:
    - uses: actions/checkout@v2
    - name: install-doxygen
      run: |
        sudo apt-get update
        sudo apt-get -y install mpich texlive-full texlive-generic-recommended texlive-latex-extra doxygen graphviz ghostscript
    - name: info
      run: |
        doxygen -v
        cmake --version
    - name: install-ginkgo
      run: |
        pushd .
        cd ${HOME}
        mkdir install
        git clone https://github.com/ginkgo-project/ginkgo.git
        cd ginkgo
        git checkout expt-develop
        mkdir build
        cd build
        cmake -DCMAKE_INSTALL_PREFIX=${HOME}/install -DGINKGO_BUILD_BENCHMARKS=off -DGINKGO_BUILD_EXAMPLES=off -DGINKGO_BUILD_TESTS=off -DGINKGO_BUILD_OMP=off -DGINKGO_BUILD_REFERENCE=off -DGINKGO_BUILD_CUDA=off ..
        make -j10
        make install
        export Ginkgo_DIR=${HOME}/install
        echo $Ginkgo_DIR
        popd
    - name: build-doc 
      run: |
        mkdir -p build-doc && pushd build-doc
        cmake -DCMAKE_PREFIX_PATH=${HOME}/install -DSCHWARZ_BUILD_CHOLMOD=off -DSCHWARZ_BUILD_METIS=off -DSCHWARZ_WITH_HWLOC=off -DSCHWARZ_BUILD_CUDA=off -DSCHWARZ_BUILD_DOC=on -DSCHWARZ_DOC_GENERATE_PDF=on ..
        make usr
        make pdf
        popd
        # publish it
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        github_token: ${{ secrets.GITHUB_TOKEN }}
        git clone git@github.com:pratikvn/schwarz-lib.git -b gh-pages gh-pages-repo
        rm -rf gh-pages-repo/doc/build-doc-ref
        mkdir -p gh-pages-repo/doc
        mkdir -p gh-pages-repo/doc/pdf
        cp -r build-doc/doc/usr gh-pages-repo/doc/build-doc-ref
        cp build-doc/doc/pdf.pdf gh-pages-repo/doc/pdf/build-doc-ref.pdf
        export CURRENT_SHA="$(git rev-parse --short HEAD)"
        cd gh-pages-repo
        git add -A
        git diff --quiet HEAD ||
            (git commit -m "Update documentation from ${CURRENT_SHA}")
    - uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/upload-artifact@v1.0.0
      with:
        name: pdf-doc 
        path: build-doc/doc/pdf.pdf 
